#!/bin/bash

# Array of week numbers and dates
weeks=(
    "Week 1 September 09"
    "Week 2 September 16"
    "Week 3 September 23"
    "Week 4 September 30"
    "Week 5 October 07"
    "Week 6 October 14"
    "Week 7 October 21"
    "Week 8 October 28"
    "Week 9 November 04"
    "Week 10 November 11"
    "Week 11 November 18"
    "Week 12 November 25"
    "Week 13 December 02"
    "Week 14 December 09"
)

# Loop through the array and create each file
for week in "${weeks[@]}"; do
    
   
    # Create the retrospective file
    retro_filename="${week// /-}-retrospective.md"
    
    # Check if the retrospective file already exists
    # if [ -e "$retro_filename" ]; then
    #     echo "Error: File $retro_filename already exists. Exiting."
    #     exit 1
    # fi
    
    # Create the retrospective file with the provided content
    {
        echo "# Retrospective Document Template"
        echo ""
        echo "## Team Name"
        echo "[Insert Team Name Here]"
        echo ""
        echo "## Date"
        echo "$week"
        echo ""
        echo "## Participants"
        echo "- [Team Member 1]"
        echo "- [Team Member 2]"
        echo "- [Team Member 3]"
        echo "- [Team Member 4]"
        echo "- [Team Member 5]"
        echo ""
        echo "---"
        echo ""
        echo "## Overview"
        echo "Briefly describe the purpose of this retrospective and what you aim to achieve."
        echo ""
        echo "---"
        echo ""
        echo "## What Went Well"
        echo "List the things that went well during the project."
        echo "-"
        echo "-"
        echo "-"
        echo ""
        echo "---"
        echo ""
        echo "## What Could Be Improved"
        echo "List the areas where there is room for improvement."
        echo "-"
        echo "-"
        echo "-"
        echo ""
        echo "---"
        echo ""
        echo "## Action Items"
        echo "Identify actionable steps that can be taken to improve future projects."
        echo "1."
        echo "2."
        echo "3."
        echo ""
        echo "---"
        echo ""
        echo "## Individual Self-Assessments"
        echo "### [Team Member 1]"
        echo "- **Achievements and Contributions:**"
        echo "  -"
        echo "- **Challenges Faced:**"
        echo "  -"
        echo "- **Areas for Improvement:**"
        echo "  -"
        echo "- **Feedback and Suggestions:**"
        echo "  -"
        echo ""
        echo "### [Team Member 2]"
        echo "- **Achievements and Contributions:**"
        echo "  -"
        echo "- **Challenges Faced:**"
        echo "  -"
        echo "- **Areas for Improvement:**"
        echo "  -"
        echo "- **Feedback and Suggestions:**"
        echo "  -"
        echo ""
        echo "### [Team Member 3]"
        echo "- **Achievements and Contributions:**"
        echo "  -"
        echo "- **Challenges Faced:**"
        echo "  -"
        echo "- **Areas for Improvement:**"
        echo "  -"
        echo "- **Feedback and Suggestions:**"
        echo "  -"
        echo ""
        echo "### [Team Member 4]"
        echo "- **Achievements and Contributions:**"
        echo "  -"
        echo "- **Challenges Faced:**"
        echo "  -"
        echo "- **Areas for Improvement:**"
        echo "  -"
        echo "- **Feedback and Suggestions:**"
        echo "  -"
        echo ""
        echo "### [Team Member 5]"
        echo "- **Achievements and Contributions:**"
        echo "  -"
        echo "- **Challenges Faced:**"
        echo "  -"
        echo "- **Areas for Improvement:**"
        echo "  -"
        echo "- **Feedback and Suggestions:**"
        echo "  -"
        echo ""
        echo "---"
        echo ""
        echo "## Overall Team Assessment"
        echo "Reflect on the team’s performance as a whole."
        echo "- **Team Strengths:**"
        echo "  -"
        echo "- **Areas for Improvement:**"
        echo "  -"
        echo "- **Suggestions for Future Projects:**"
        echo "  -"
        echo ""
        echo "---"
        echo ""
        echo "## Additional Comments"
        echo "Add any additional comments or notes that may be relevant."
        echo "-"
    } > "$retro_filename"
done

echo "Markdown documents created successfully."